version: "3.8"
services:
  pharmacy-recommendation-redis: # 서비스명
    container_name: pharmacy-recommendation-redis
    build: # 도커 파일 이름 & 위치
      dockerfile: Dockerfile
      context: ./redis
    image: junesworld/pharmacy-recommendation-redis # docker hub 이름으로 명시해야한다!
    ports:
      - "6379:6379"
  pharmacy-recommendation-database:
    container_name: pharmacy-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: junesworld/pharmacy-recommendation-database
    environment:
      - MARIADB_DATABASE=pharmacy-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD} # 외부에서 환경변수 주입 .env(.gitignore)
    volumes: # mariadb.cnf 참조하여 DB 초기화
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"