spring:
  profiles:
    active: local #default
    group:
      local: # local, common profile? ???? ?? ?????? ??
        - common
      prod: # prod, common profile? ???? ?? ?????? ??
        - common

---

spring:
  config:
    activate:
      on-profile: common # application-common.yml ? ??? ??

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: prod